services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ../configs/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../configs/tls/combined.pem:/etc/haproxy/tls/combined.pem:ro
    ports:
      - "${TLS_PORT:-6443}:443"
    depends_on:
      - engine
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256M
